# Generated by Django 4.0.4 on 2022-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapp', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='vehiculos',
            field=models.ManyToManyField(related_name='vehiculos', to='pruebaapp.vehiculo'),
        ),
    ]
