# Generated by Django 4.0.4 on 2022-05-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=200)),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (0, 'Indefinido'), (-1, 'Femenino')])),
            ],
        ),
    ]
