# Generated by Django 4.0.4 on 2022-05-27 18:40

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='razon',
        ),
        migrations.AddField(
            model_name='pedido',
            name='razon_cancelacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Pedido Realizado'), (2, 'Pedido confirmado por el restaurante'), (3, 'Pedido aceptado por el chofer'), (4, 'Chofer esperando el pedido en el restaurante'), (5, 'Chofer ya tiene el pedido'), (6, 'Pedido Entregado'), (-1, 'Cancelado')], default=1),
        ),
    ]
