# Generated by Django 4.0.4 on 2022-06-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='longitud',
            new_name='longitude',
        ),
    ]
