# Generated by Django 4.0.3 on 2022-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Masculino'), (0, 'Indefinido'), (-1, 'Femenino')]),
        ),
    ]
