# Generated by Django 4.0.3 on 2022-04-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'Perro'), (1, 'Gato'), (2, 'Loro'), (3, 'Mapache')])),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='personas.persona')),
            ],
        ),
    ]
