# Generated by Django 4.0.4 on 2022-06-30 05:59

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud_origen', models.TextField()),
                ('latitud_origen', models.TextField()),
                ('longitud_destino', models.TextField()),
                ('latitud_destino', models.TextField()),
                ('estado', django_fsm.FSMIntegerField(choices=[(1, 'Pedido Realizado y en espera de envio'), (2, 'Pedido en camino'), (3, 'Pedido entregado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario_id', models.IntegerField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RastreoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega_update', models.IntegerField()),
                ('nombre_ubicacion', models.TextField()),
                ('longitud', models.TextField()),
                ('latitud', models.TextField()),
                ('entrega_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_rastreo', to='entrega.entrega')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='pedido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_entrega', to='entrega.pedido'),
        ),
    ]
