# Generated by Django 4.0.4 on 2022-07-01 10:30

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude_origen', models.TextField()),
                ('latitude_origen', models.TextField()),
                ('longitude_destino', models.TextField()),
                ('latitude_destino', models.TextField()),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'Pedido Creado'), (1, 'Pedido Realizado y en espera de envio'), (2, 'Pedido en camino'), (3, 'Pedido entregado')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario_id', models.IntegerField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RastreoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField()),
                ('nombre_ubicacion', models.TextField()),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrega_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_rastreo', to='entrega.entrega')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_id', models.IntegerField()),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_detalle', to='entrega.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='pedido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_entrega', to='entrega.pedido'),
        ),
    ]
