# Generated by Django 4.0.4 on 2022-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastreoentrega',
            name='entrega_update',
        ),
        migrations.AddField(
            model_name='rastreoentrega',
            name='estado',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
