# Generated by Django 4.0.4 on 2022-06-30 20:54

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0002_remove_rastreoentrega_entrega_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Pedido Creado'), (1, 'Pedido Realizado y en espera de envio'), (2, 'Pedido en camino'), (3, 'Pedido entregado')], default=0),
        ),
    ]
