# Generated by Django 4.0.4 on 2022-05-05 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_reunion', models.CharField(max_length=200)),
                ('fecha_hora_reunion', models.DateField()),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reunionowner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='usertoreunion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
