# Generated by Django 4.0.4 on 2022-05-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_reunion', models.CharField(max_length=200)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
