http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  apipersonas:
    host: localhost
    paths: '/pruebaapp/personas'
  apimascotas:
    host: localhost
    paths: '/pruebaapp/mascotas'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  personasapi:
    url: 'http://127.0.0.1:8000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - apipersonas
      - apimascotas
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: personasapi 
              changeOrigin: true
  pruebapipeline:
    apiEndpoints:
      - api
    policies:
      - jwt:
          - action:
              secretOrPublicKey: 'django-insecure-ljg^!ji2e5k)g#nf$83jkq@jvsjb#o%ny&=ow$tb(k421%i362'
              checkCredentialExistence: false
      - request-transformer:
          action:
            body:
              add:
                user: req.user
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
