# Generated by Django 4.0.3 on 2022-04-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('registro', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('ci', models.IntegerField()),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (0, 'Indefinido'), (-1, 'Femenino')])),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('ci', models.IntegerField()),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (0, 'Indefinido'), (-1, 'Femenino')])),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('semestre', models.IntegerField()),
                ('carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=200)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='entidades.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='entidades.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='entidades.alumno')),
                ('oferta_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_materia', to='entidades.ofertamateria')),
            ],
        ),
    ]
